apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world-ns
spec:
  selector:
    app: "hello-world"
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5678
